THEME_LABELS = {
    "support_ukraine": "Support for Ukraine",
    "eastern_flank_nato_deterrence": "Eastern Flank / NATO Deterrence",
    "romania_republic_of_moldova": "Romania - Republic of Moldova",
    "russia_regional_implications": "Russia: Actions, Positioning, and Regional Implications",
    "eu_regional_security": "EU and Regional Security",
    "black_sea_regional_security": "Black Sea and Regional Security",
    "other_mixed": "Other / Mixed",
}

THEME_KEYWORDS = {
    "support_ukraine": [
        "ukraine",
        "ukrainian",
        "ukrainians",
        "support for ukraine",
        "support to ukraine",
        "continued support for ukraine",
        "aid to ukraine",
        "ukraine aid",
        "ukrainian aid",
        "assistance to ukraine",
        "war in ukraine",
        "russia's war against ukraine",
        "security assistance to ukraine",
        "military aid to ukraine",
        "military support to ukraine",
        "humanitarian aid to ukraine",
        "air defence for ukraine",
        "weapons for ukraine",
        "ammunition for ukraine",
        "standing with ukraine",
        "solidarity with ukraine",
        "reconstruction of ukraine",
        "recovery of ukraine",
    ],

    "eastern_flank_nato_deterrence": [
        "eastern flank",
        "nato eastern flank",
        "strengthening nato's eastern flank",
        "deterrence",
        "deterrence and defence",
        "nato deterrence",
        "collective defence",
        "forward defence",
        "forward presence",
        "enhanced forward presence",
        "allied presence",
        "allied forces",
        "nato forces",
        "multinational battlegroup",
        "battlegroup",
        "troop presence",
        "reinforcement",
        "reinforcements",
        "force posture",
        "military posture",
        "defence posture",
        "readiness",
        "high readiness",
        "air policing",
        "integrated air and missile defence",
        "missile defence",
        "defence and deterrence",
        "eastern allies",
        "frontline allies",
        "territorial defence",
        "article 5",
        "collective security",
        "nato exercises",
        "military exercises",
        "exercise",
        "host nation support",
        "regional defence plans",
        "defence plans",
        "allied reinforcement",
    ],

    "romania_republic_of_moldova": [
        "republic of moldova",
        "moldova",
        "romania and the republic of moldova",
        "romania-republic of moldova",
        "bilateral cooperation",
        "bilateral relations",
        "relations with the republic of moldova",
        "support for the republic of moldova",
        "support to the republic of moldova",
        "supporting the republic of moldova",
        "stability and resilience of the republic of moldova",
        "strengthening the resilience of the republic of moldova",
        "republic of moldova's resilience",
        "european future of the republic of moldova",
        "european integration of the republic of moldova",
        "eu accession process",
        "republic of moldova's accession process",
        "republic of moldova's european integration",
        "chisinau",
        "chisinu",
        "ungheni",
        "iasi-ungheni",
        "common border",
        "border crossing points",
        "energy interconnections",
        "energy independence of the republic of moldova",
        "high-voltage lines",
        "bridges",
        "railway connection",
        "electrification",
        "infrastructure projects",
        "sectoral cooperation",
        "mihai popsoi",
        "deputy prime minister and minister of foreign affairs of the republic of moldova",
        "parliamentary elections in the republic of moldova",
        "foreign interference attempts",
    ],

    "russia_regional_implications": [
        "russia",
        "russian",
        "kremlin",
        "moscow",
        "russian federation",
        "russia's war against ukraine",
        "russian aggression",
        "russian invasion",
        "russian attacks",
        "russian strikes",
        "russian military",
        "russian forces",
        "russian troops",
        "russian drones",
        "russian missiles",
        "russian disinformation",
        "hybrid threats",
        "foreign interference",
        "destabilisation",
        "destabilization",
        "regional implications",
        "regional consequences",
        "security implications",
        "russian actions",
        "russian positioning",
        "hostile actions",
        "aggressive actions",
        "revisionist policy",
        "war of aggression",
        "threat posed by russia",
    ],

    "eu_regional_security": [
        "european union",
        "eu",
        "european commission",
        "european council",
        "european parliament",
        "eu member states",
        "eu foreign affairs council",
        "eu enlargement",
        "eu accession",
        "accession process",
        "candidate country",
        "european integration",
        "integration into the european union",
        "eu support",
        "eu assistance",
        "eu sanctions",
        "restrictive measures",
        "common foreign and security policy",
        "cfsp",
        "european peace facility",
        "regional security",
        "security of europe",
        "european security",
        "security architecture",
        "strategic autonomy",
        "resilience in the european union",
        "neighbourhood policy",
        "eastern partnership",
    ],

    "black_sea_regional_security": [
        "black sea",
        "black sea region",
        "security in the black sea region",
        "black sea security",
        "black sea area",
        "black sea basin",
        "freedom of navigation in the black sea",
        "navigation in the black sea",
        "maritime security",
        "naval security",
        "sea lines of communication",
        "ports on the black sea",
        "grain corridor",
        "black sea grain initiative",
        "mines in the black sea",
        "regional security in the black sea",
        "security architecture in the black sea",
        "russian activity in the black sea",
        "allied presence in the black sea",
        "strategic importance of the black sea",
        "black sea deterrence",
        "black sea stability",
    ],

    "other_mixed": [],
}