"""
Design tokens for the OSINT Regional Security Monitor dashboard.

These tokens define the visual foundation of the dashboard and should be the
single source of truth for colors, spacing, typography, layout, tables, badges,
and reusable UI surfaces.
"""

DESIGN_TOKENS = {
    "colors": {
        "background_primary": "#0A1220",
        "background_secondary": "#111C30",
        "surface_primary": "#16243D",
        "surface_secondary": "#1B2B47",
        "border_subtle": "#223250",
        "border_strong": "#2D4266",
        "text_primary": "#EAF1FB",
        "text_secondary": "#9FB0C9",
        "text_muted": "#7C8CA8",
        "accent_primary": "#2D6CDF",
        "accent_hover": "#4B86F5",
        "accent_active": "#1F5ED1",
        "success": "#22C55E",
        "warning": "#F59E0B",
        "danger": "#EF4444",
        "info": "#38BDF8",
    },
"spacing": {
        "space_0": "0rem",
        "space_1": "0.25rem",
        "space_2": "0.5rem",
        "space_3": "0.75rem",
        "space_4": "1rem",
        "space_5": "1.25rem",
        "space_6": "1.5rem",
        "space_8": "2rem",
        "space_10": "2.5rem",
        "space_12": "3rem",
        "space_16": "4rem",
        "space_20": "5rem",
    },
    "radius": {
        "none": "0",
        "sm": "0.375rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.25rem",
        "pill": "9999px",
    },
    "typography": {
        "font_family_base": (
            '"Inter", "Segoe UI", "Roboto", "Helvetica Neue", Arial, sans-serif'
        ),
        "font_family_mono": (
            '"JetBrains Mono", "SFMono-Regular", "Consolas", monospace'
        ),
        "font_size_xs": "0.75rem",
        "font_size_sm": "0.875rem",
        "font_size_md": "1rem",
        "font_size_lg": "1.125rem",
        "font_size_xl": "1.25rem",
        "font_size_2xl": "1.5rem",
        "font_size_3xl": "1.875rem",
        "font_size_4xl": "2.25rem",
        "font_weight_regular": 400,
        "font_weight_medium": 500,
        "font_weight_semibold": 600,
        "font_weight_bold": 700,
        "line_height_tight": 1.2,
        "line_height_normal": 1.5,
        "line_height_relaxed": 1.7,
        "letter_spacing_tight": "-0.02em",
        "letter_spacing_normal": "0",
        "letter_spacing_wide": "0.02em",
    },
    "layout": {
        "page_max_width": "1600px",
        "content_max_width": "1400px",
        "sidebar_width": "320px",
        "header_height": "64px",
        "kpi_card_min_height": "120px",
        "detail_panel_min_height": "320px",
        "table_row_min_height": "56px",
        "container_padding_x": "1.5rem",
        "container_padding_y": "1rem",
        "section_gap": "1.5rem",
        "grid_gap": "1rem",
    },
    "table": {
        "header_background": "#111C30",
        "header_text": "#EAF1FB",
        "row_background": "#16243D",
        "row_background_alt": "#142038",
        "row_hover": "#1E355A",
        "row_selected": "#223C63",
        "row_border": "#223250",
        "cell_text": "#EAF1FB",
        "cell_text_muted": "#9FB0C9",
        "header_font_size": "0.875rem",
        "cell_font_size": "0.875rem",
        "header_font_weight": 600,
        "cell_font_weight": 400,
        "cell_padding_y": "0.75rem",
        "cell_padding_x": "0.875rem",
        "title_max_lines": 2,
        "preview_max_lines": 1,
        "preview_max_lines_compact": 2,
        "sticky_header": True,
    },
    "badges": {
        "height": "1.75rem",
        "padding_x": "0.625rem",
        "padding_y": "0.25rem",
        "gap": "0.375rem",
        "border_radius": "9999px",
        "font_size": "0.75rem",
        "font_weight": 600,
        "primary_background": "#1B3F78",
        "primary_text": "#EAF1FB",
        "secondary_background": "#223250",
        "secondary_text": "#9FB0C9",
        "success_background": "#163A27",
        "success_text": "#C8F7D4",
        "warning_background": "#4A3312",
        "warning_text": "#FDE7B0",
        "danger_background": "#4A1F24",
        "danger_text": "#F9C7CD",
        "info_background": "#15384A",
        "info_text": "#C8F1FF",
    },
    "cards": {
        "background": "#16243D",
        "border": "#223250",
        "border_radius": "1rem",
        "padding": "1.25rem",
        "title_font_size": "0.875rem",
        "value_font_size": "1.875rem",
        "label_text": "#9FB0C9",
        "value_text": "#EAF1FB",
        "shadow": "0 8px 24px rgba(0, 0, 0, 0.18)",
    },
}